name: 'Setup Node + NPM + Install Dependencies'
description: 'Setup Node + NPM + Install Dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: CommUnity/package-lock.json  # Cache key refers to package-lock.json inside CommUnity

    - name: Install Dependencies
      run: npm install
      working-directory: ./CommUnity  # Ensure npm install runs inside CommUnity
      shell: bash
