name: 'Setup Node + NPM + Install Dependencies'
description: 'Setup Node + NPM + Install Dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - name: Install Dependencies
      run: npm install
      shell: bash
