name: Lint TS (eslint, prettier)

on:
  push:
    branches: [main, master]
    paths:
      - 'CommUnity/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'CommUnity/**'

jobs:
  lint:
    name: Lint TS (eslint, prettier)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CommUnity  # 👈 Makes all run: steps operate inside CommUnity/

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + NPM + install deps
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Make sure this is the version your project requires
        working-directory: CommUnity  # 👈 Run setup inside CommUnity/

      - name: 📦 Install Project Dependencies
        run: npm install --frozen-lockfile  # Use npm install instead of pnpm
        working-directory: CommUnity  # 👈 Run inside CommUnity/

      - name: 🏃‍♂️ Run ESLint PR
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: ". --ext .js,.jsx,.ts,.tsx"
          workdir: CommUnity  # 👈 Tell Reviewdog to lint files in CommUnity/

      - name: 🏃‍♂️ Run ESLint Commit
        if: github.event_name != 'pull_request'
        run: npm run lint  # Use npm run instead of pnpm
